"""
TestScheduler — generated by the HostScheduler scheduler assistant.

To make this your own:
  1. Rename / replace handlers in handlers/ and update HANDLER_REGISTRY
  2. Update SCHEDULER_INFO labels and api entries
  3. Update the database schema in db.py
  4. Add or modify routes in router.py
  5. Restart the kernel to pick up changes (Stop Kernel & Register button)
"""
import threading
import time

from schedhost.core import task_queue
from schedhost.core.scheduler_base import SchedulerBase
from schedhost.core.config import POLL_INTERVAL_SECONDS
from schedulers.test_scheduler.handlers.string_handlers import (
    RemoveAlternateWordsHandler,
    AddWordHandler,
    DeleteWordHandler,
)
from schedulers.test_scheduler import db as scheduler_db

MAX_CONCURRENT = 4

# ---------------------------------------------------------------------------
# SCHEDULER_INFO — read by the frontend to build the dynamic tab.
# Update to reflect your scheduler's actual API and description.
# ---------------------------------------------------------------------------
SCHEDULER_INFO = {
    "name":        "test",
    "label":       "Test",
    "description": "Test scheduler",
    "api": [
        {"method": "GET",    "path": "/test/results",        "label": "List results",  "description": "List all processed results"},
        {"method": "POST",   "path": "/test/process",        "label": "Process",       "description": "Submit input for processing"},
        {"method": "DELETE", "path": "/test/results/{id}", "label": "Delete result", "description": "Delete a result by id"},
    ],
}


class TestScheduler(SchedulerBase):
    NAME             = "test"
    SCHEDULER_INFO   = SCHEDULER_INFO
    HANDLER_REGISTRY = {
        "remove_alternate": {
            "handler":     RemoveAlternateWordsHandler,
            "description": "Remove every other word from the input string",
            "input_label": "String",
        },
        "add_word": {
            "handler":     AddWordHandler,
            "description": "Append a word to the end of the string",
            "input_label": "String",
            "options":     {"word": "Word to append (default: 'hello')"},
        },
        "delete_word": {
            "handler":     DeleteWordHandler,
            "description": "Remove a specific word from the string",
            "input_label": "String",
            "options":     {"word": "Word to remove"},
        },
    }

    def __init__(self):
        super().__init__()
        self._lock    = threading.Lock()
        self._running = 0

    def run(self):
        task_types = [f"{self.NAME}_{op}" for op in self.HANDLER_REGISTRY]
        print(f"[test-scheduler] started — handling: {', '.join(task_types)}")
        while not self._stop_event.is_set():
            with self._lock:
                if self._running < MAX_CONCURRENT:
                    task = task_queue.get_next_pending_for_types(task_types)
                    if task:
                        self._running += 1
                        threading.Thread(
                            target=self._run_task, args=(task,), daemon=True
                        ).start()
            self._sleep(POLL_INTERVAL_SECONDS)
        print(f"[test-scheduler] stopped")

    def _run_task(self, task: dict):
        task_id  = task["id"]
        short_id = task_id[:8]
        op       = task["agent_type"].removeprefix(f"{self.NAME}_")
        t0 = time.time()
        ok = True
        err = None
        result = ""
        try:
            handler = self.HANDLER_REGISTRY[op]["handler"]()
            task_queue.mark_running(task_id)
            print(f"[test-scheduler] running {short_id} ({task['agent_type']})")
            result = handler.handle(task["prompt"], task.get("options") or {})
            scheduler_db.save_result(op, task["prompt"], result)
        except Exception as e:
            ok = False
            err = str(e)
        finally:
            # log before mark_done/failed so activity is written before the IPC notify fires
            self.log_activity(
                operation=op,
                prompt_len=len(task.get("prompt", "")),
                result_len=len(result),
                duration_ms=int((time.time() - t0) * 1000),
                ok=ok,
                error=err,
            )
            if ok:
                task_queue.mark_done(task_id, result)
                print(f"[test-scheduler] done    {short_id}")
            else:
                task_queue.mark_failed(task_id, err)
                print(f"[test-scheduler] failed  {short_id}: {err}")
            with self._lock:
                self._running = max(0, self._running - 1)
